### ISSUE TITLE
Bursting and Shrine of the Storm

### ISSUE THREAD

**Issue by codeguru42** [domainzero/mythicpl.us#102]
Under Bursting you have

> Shrine of the Storm is especially bad with this affix

Is this wording still necessary? If I understand correctly, patch 8.1.5 modified the bubbles so that they no longer apply bursting. I haven't confirmed this yet and there may be other reasons that SotS is particularly difficult with bursting.

**Comment by domainzero** [comment]
I have no problem changing the wording.
I haven't played since 8.1 so the site could probably use some blanket revisions for things I had previously written.
