### ISSUE TITLE
Home page have a JS error on getAffixes

### ISSUE THREAD

**Issue by amarques** [domainzero/mythicpl.us#121]
Uncaught TypeError: Cannot read property 'classList' of null
    at highlightCurrentAffixes (?g=js:1)
    at XMLHttpRequest.xhr.onreadystatechange (?g=js:2)

This error impact the languages on the website.

**Comment by domainzero** [comment]
I was missing this week's affixes in the table.
Adjusted the table and the `getaffixes.js` script.
