### ISSUE TITLE
small suggestion

### ISSUE THREAD

**Issue by zzzoma** [domainzero/mythicpl.us#14]
At the very top you list the affixes for the week and then you scroll down a bit and have all the affixes color coded to reflect difficulty.  Any chance the text at the top could also have that color coding?

**Comment by domainzero** [comment]
I thought about doing that but wasn't sure if it would be too much/too busy to look at right away.
I'll putz around with it.

**Comment by JosKrause** [comment]
Perhaps show the difficulty color on hover?
