### ISSUE TITLE
Valor Section Outdated

### ISSUE THREAD

**Issue by Fleck2021** [domainzero/mythicpl.us#144]
The upgrade thresholds are out of date, as per ~last minute change before patch/season

1500 was replaced with 1400 and 1700 tiers, there are a few other changes too

Actual wowhead guide is wrong too, but this change news has it right I believe:
https://www.wowhead.com/news/requirements-to-upgrade-gear-with-valor-changing-in-season-2-of-mythic-322919

<html>
<body>

N/A | Rank | Item Level | Requirements
-- | -- | -- | --
  | 1 | 210 |   |  
  | 2 | 213 |   |  
  | 3 | 216 |   |  
  | 4 | 220 |   |  
  | 5 | 223 |   |  
  | 6 | 226 |   |  
  | 7 | 229 | <del>Attain a Mythic+ Rating of at least 750 during Shadowlands Season Two.</del><ins>Attain a Mythic+ Rating of at least 600 during Shadowlands Season Two.</ins> |  
  | 8 | 233 | <del>Attain a Mythic+ Rating of at least 750 during Shadowlands Season Two.</del><ins> Attain a Mythic+ Rating of at least 1000 during Shadowlands Season Two.</ins> |  
  | 9 | 236 | <del>Attain a Mythic+ Rating of at least 1500 during Shadowlands Season Two.</del><ins> Attain a Mythic+ Rating of at least 1000 during Shadowlands Season Two.</ins> |  
  | 10 | 239 | <del>Attain a Mythic+ Rating of at least 1500 during Shadowlands Season Two.</del><ins> Attain a Mythic+ Rating of at least 1400 during Shadowlands Season Two.</ins> |  
  | 11 | 242 | <del>Attain a Mythic+ Rating of at least 2000 during Shadowlands Season Two.</del><ins> Attain a Mythic+ Rating of at least 1700 during Shadowlands Season Two. |  
  | 12 | 246 | Attain a Mythic+ Rating of at least 2000 during Shadowlands Season Two.

</body>
</html>

**Comment by domainzero** [comment]
Hey @Fleck2021 

Finally got around to getting this addressed on the site.
Thanks for the input!
