### ISSUE TITLE
Loot Sheet 

### ISSUE THREAD

**Issue by narabug** [domainzero/mythicpl.us#15]
I created a M+ spreadsheet for my own use in determining the most valuable content to run:

https://docs.google.com/spreadsheets/d/10R6HYTsjkfXT_FxHEsceoHWDlkrKgECEOmvzkliwrcQ/edit?usp=sharing

There are 4 drop-down selectors on the top right for the following:

- **Modifier**: This is the base chance that the item will roll with increased item level.
- **Increased iLvl**: This is the chance that an item will continue to increase item level after the first +5, and it is used recursively until it fails to increase.
- **Shared Loot**: This is how many people in the party that are eligible for the item that you are targeting.
- **Target iLvl**:  This is the desired level of the item.

Some very quick conclusions can be drawn from this, despite not knowing the exact drop chances -

- For the purpose of obtaining gear, It is **always** best to run a +3 of the highest difficulty that you can consistently meet the +3 timer in.
- The highest increase in statistical probability of getting the best-quality items is from +8 to +9.
- Since the highest decrease in probability that you can reasonably meet the +3 timer is a +10, this means that the ideal difficulty to run for the best gear would be +9.

**Comment by domainzero** [comment]
I'll include this in the useful stuff section and update the loot section.
Thanks!
