### ISSUE TITLE
Random question: Where do you get your info on the affix schedule?

### ISSUE THREAD

**Issue by adamhammes** [domainzero/mythicpl.us#152]
Thank you for the site, it's super helpful!

My guildies and I were trying to figure out the 9.2 affix schedule on our own, and were curious as to how you figured it out faster than us :-) Teach us your secrets!

**Comment by domainzero** [comment]
First, thanks for the kind words. I really appreciate it.  
  
The schedule is usually pretty static. This season only has only had one week with an affix combo that was different from last season (so far). The only real shakeup that has happened in a few years(!) was during 9.1.  
  
Blizzard doesn't give out the schedule information ahead of time as far as I know.
