### ISSUE TITLE
Adding other regions

### ISSUE THREAD

**Issue by Gooberish** [domainzero/mythicpl.us#17]
Would be nice if you could add other regions, love your page and if you could have china shown on the weekly affixes it would be baller! Thanks again for a great page.

**Comment by domainzero** [comment]
I haven't actually seen the Chinese region current affixes.
Do you know where I can get their current affixes? Should be able to schedule it after that.

**Comment by domainzero** [comment]
Right on, I'll make a note somewhere that CN follows the same schedule but starts on Thursday.

Thanks!
