### ISSUE TITLE
Typo in ilvl rewards of Great Vault lvl 17 (4441)

### ISSUE THREAD

**Issue by Jodsderechte** [domainzero/mythicpl.us#200]
i think the title speaks for itself. I spend like 2 min trying to find the correct file to make a pull request with the change directly.

**Comment by Jodsderechte** [comment]
found it and opened a pull request https://github.com/domainzero/mythicpl.us/pull/201

**Comment by domainzero** [comment]
Thanks! Merging in the PR and closing this out.
