### ISSUE TITLE
table with key level you get from weekly chest

### ISSUE THREAD

**Issue by chuDr3t4** [domainzero/mythicpl.us#24]
maybe under the loot table which describes loot ilvl from weekly chest?
i myself don't have info about every key level drop and can't find this info easily.
12->9, 13->10, 15->11 and that's the extent of my knowledge.

**Comment by domainzero** [comment]
I'll see if I can get some solid info on this and build a table or something.

**Comment by chuDr3t4** [comment]
This is what I experienced myself:
10>7
12>9
13>10
15>11
16>12
17>13
and my guildie told me 19>14

**Comment by Gnarfoz** [comment]
I can confirm at least 15 -> 11 and 16 -> 12 out of those.

**Comment by domainzero** [comment]
Based on the pattern then we could assume 18 probably goes down to 14.

**Comment by domainzero** [comment]
In the process of cleaning up some stuff on the site, will implement this when I have it in a good spot.
After I threw the table in there was just too much stuff on screen at once.

**Comment by chuDr3t4** [comment]
11, 14 and 19 confirmations coming when EU reset happens : )

**Comment by Gnarfoz** [comment]
Can confirm 19 > 14.

**Comment by chuDr3t4** [comment]
11>8
14>10
19>14

**Comment by domainzero** [comment]
Key level at end of the week  |    | Key level at start of next week
-------------------------------- | - | --------------------------------
10 | > | 7
11 | > | 8
12 | > | 9
13 | > | 10
14 | > | 10
15 | > | 11
16 | > | 12
17 | > | 13
18 | > | 14
19 | > | 15

Look good?

**Comment by Gnarfoz** [comment]
Maybe add a * to 18, because it's assumption-based at the moment, but the rest seems fine/confirmed.

**Comment by domainzero** [comment]
Sounds good. I'll get this pushed out on the next commit.

**Comment by Gnarfoz** [comment]
Addendum: 21 -> 15

**Comment by chuDr3t4** [comment]
21 > 15
22 > 16

**Comment by chuDr3t4** [comment]
18 > 13, 2 reports from guildies

**Comment by chuDr3t4** [comment]
20 > 15 cit needed

**Comment by domainzero** [comment]
You got it folks.

**Comment by chuDr3t4** [comment]
You got explanation kinda wrong and it can confuse some ppl. This key you get from the Cache has nothing to do with the key you had. Everything is derived from highest completed level, similar to determining the loot you get. You could have a +2 key, join +15 party, complete the dungeon and get +11 from next Cache, not touching your own +2. This is why I originally suggested including it in the loot table. Not the best idea, but you feel me?

Also, on another note. My friend told me this curious case he had, hearing that I gather this data. He told me that once he didn't complete any dungeon and still got high key from the 0-level cache. And now he tried to reproduce it on these 2 weeks.

Week 1: completed 15. Cache 1: 11.
Week 2: completed 0. Cache 2: 8.
Week 3: completed 7. Cache 3: 8.

**Comment by domainzero** [comment]
Agh, you're right. Brain was fried, I'll fix it.

**Comment by domainzero** [comment]
Alright I cleared up the language:

> Your keystone will degrade based on the highest keystone run **you completed** the previous week. Below is a table showing what keystone you'll get out of your cache at the end of the week.

**Comment by Gnarfoz** [comment]
Adding another column to the loot table, indicating which keystone you'll get next week would eliminate the entire "keystone next week" table, though. That one almost fills an entire screen for me as it is.
Should be a net decrease of overall page length.
Also, as it is, there's no "quick jump thing" at the top of the page for the keystone table. Integrating it into the loot table would kill that bird with the same stone.

It would also mean padding the "loot at end" and "weekly chest" columns with repeating numbers, clearly indicating that you don't get better loot from doing anything above +15.
Which would perhaps allow thinning out the explanation text a bit.


> He told me that once he didn't complete any dungeon and still got high key from the 0-level cache

I have nothing to support this hypothesis, but: maybe you don't go below a certain level after completing Keystone Conqueror/Keystone Master? Just an idea. Would need someone abstaining from M+ for a couple of weeks to confirm.

**Comment by domainzero** [comment]
> Adding another column to the loot table, indicating which keystone you'll get next week would eliminate the entire "keystone next week" table, though. That one almost fills an entire screen for me as it is.
Should be a net decrease of overall page length.
Also, as it is, there's no "quick jump thing" at the top of the page for the keystone table. Integrating it into the loot table would kill that bird with the same stone.

That's a good point. I'll see what it looks like with the one table having all this information. I might have to adjust the styling but w/e.

> Would need someone abstaining from M+ for a couple of weeks to confirm.

Gotcha there, I'll log in when I get off work to see if I have a keystone waiting.

**Comment by domainzero** [comment]
@Gnarfoz Are we good on this one do you think?
I didn't have any keystone waiting for me after I logged in from a few week hiatus after finishing a +15.

**Comment by Gnarfoz** [comment]
I didn't even have a keystone after missing one week of M+.
Seems like there is no "raised floor" associated with completing +15 once or anything.
I'll check what key I get this week when I finish my first one (but I guess it'll be dependent on which level of M+ I get it from).

**Comment by Gnarfoz** [comment]
I got a +8 key from our +12, after not having a key at all last week.
Another player from my team got +9 from the same instance after not having a key for ~4 weeks.

So I'd say taking a break of any length (i.e. any number of weeks without doing a single M+) will reset you to nothing.

**Comment by chuDr3t4** [comment]
skipped 2 weeks after doing +15 and got +8 key from +10 dungeon, but should have got +7. clearly something going on there.

**Comment by chuDr3t4** [comment]
lurked around reddits, discords and on wowhead(ap items)
this is what i got so far
http://i.imgur.com/lcs6zIJ.png

**Comment by domainzero** [comment]
Here's what i got
![chart](https://cdn.discordapp.com/attachments/239987577761824768/299021824430440450/AP_Base_Chart.png)

**Comment by Gnarfoz** [comment]
14 > 10 after 7.2

**Comment by chuDr3t4** [comment]
19 > 15 (!) after 7.2
