### ISSUE TITLE
Include "gear track" information to loot table

### ISSUE THREAD

**Issue by jonespm** [domainzero/mythicpl.us#245]
First off, great site, thanks!

The only thing I usually have to go elsewhere to reference is the gear track which was [mentioned on this WowHead article](https://www.wowhead.com/news/dragonflight-season-3-mythic-item-level-changes-need-18s-for-myth-track-335011).

It would be great if the loot table included this information somewhere for gear type. I just want to know what I need to aim for. Maybe something like this? Could just abbreviate them to V/C/H/M or something too so it doesn't take up as much horizontal space. 

Level | End of Run | Great Vault 
-- | -- | -- |
2 | 441 (Veteran 1/8) | 454 (Champion 1/8)
3 | 444 (Veteran 2/8) | 457 (Champion 2/8)
4 | 444 (Veteran 2/8) | 460 (Champion 3/8)

**Comment by domainzero** [comment]
I'll probably do this for Season 4. The last time I had this info, the table was a giant mess, but with there really only being 10 keystone levels of loot now, I think it'll probably be easier to read.

**Comment by domainzero** [comment]
This is included now.
Thanks for the issue!
