### ISSUE TITLE
Stats, tools, and guides: Keystone heroes

### ISSUE THREAD

**Issue by drunkenvalley** [domainzero/mythicpl.us#246]
The link to [Keystone Heroes](https://keystone-heroes.com/) still works, but apparently the site no longer functions, their linked [Twitter](https://twitter.com/gerrit_alex) doesn't exist anymore, and the [Discord](https://discord.com/invite/ubUjUTMdhE) also seems inactive.

![image](https://github.com/domainzero/mythicpl.us/assets/1728144/ecef1ef6-2335-4cec-a833-e28c56ba198a)

![image](https://github.com/domainzero/mythicpl.us/assets/1728144/d6975cdc-dc81-4876-bede-676543135bbd)

The last Github message dates back to '22.

![image](https://github.com/domainzero/mythicpl.us/assets/1728144/93cb553a-1f96-46cb-b838-d0af73d5e6fc)

**Comment by domainzero** [comment]
Thanks for the info. I'll get this removed.

**Comment by domainzero** [comment]
This is removed now.
Thanks for the issue!
