### ISSUE TITLE
New useful addon

### ISSUE THREAD

**Issue by Kanegasi** [domainzero/mythicpl.us#25]
I'm not sure if you saw it on r/wow, but a new very useful pugging tool for mythics appeared on the sub:

https://www.reddit.com/r/wow/comments/5uoqav/hey_reddit_i_built_a_tool_to_help_you_form_better/
http://mythicplus.help/
https://mods.curse.com/addons/wow/260666-mythic-plus-helper

I really like this and was wondering if you could include it on your site to help the author reach a wider audience.

**Comment by domainzero** [comment]
Donezo!
