### ISSUE TITLE
Site is showing the wrong affixes

### ISSUE THREAD

**Issue by Wotuu** [domainzero/mythicpl.us#253]
Hey,

I was just doing some work and I noticed my affix list didn't match up with what was shown on Mythicpl.us. I figured I must have made a mistake and made corrections to match yours - but eventually I found out that it was not me that was wrong, but it's Mythicpl.us.

Currently it's showing as the current affixes being Fortified Entangling Bolstering, but this is not the case. The current affixes are Fortified Storming Bursting. This is showing the correct overview still: https://keystone.guru/affixes.

Raider.io run showing a run that was cleared 1 day ago with these affixes: https://raider.io/mythic-plus-runs/season-df-4/12252828-22-the-azure-vault

Further proof of historic affixes from my Discord: 
![image](https://github.com/user-attachments/assets/8a11ed9e-cadc-4cf5-84ff-8cae16c2d1ea)

**Comment by domainzero** [comment]
You're right! The deploy job was broken and the site wasn't updating with new info. I never got notified for this, and since I'm not playing the game right now I didn't notice.

Thanks for letting me know.

**Comment by Wotuu** [comment]
All good! I haven't played in a year and a half either, so sometimes I find obviously broken/wrong things as well that I simply haven't noticed before 😄 Thank you for fixing it!
