### ISSUE TITLE
Oblivion affix description is wrong 

### ISSUE THREAD

**Issue by TreeOfLearning** [domainzero/mythicpl.us#263]
It seems that the oblivion affix actually increases enemy damage done by 10%, rather than reducing damage taken. See: https://www.wowhead.com/news/xalataths-bargain-oblivion-is-this-weeks-mythic-affix-346852

Also, if I may mention a second, unrelated issue: voidbound has a typo, "rediction" rather than "reduction".

Thanks!

**Comment by domainzero** [comment]
Both of these are fixed as of #265
