### ISSUE TITLE
Adjust skittish text to get rid of "periodically drops threat"

### ISSUE THREAD

**Issue by domainzero** [domainzero/mythicpl.us#27]
I guess this is an urban legend and doesn't actually happen.

**Comment by Gnarfoz** [comment]
Evidence as to how it actually works is hard to come by... But enemies you've been tanking for a while just turning around and just obliterating someone else who is close by is pretty much what skittish is all about.
Only remedy: taunt, which of course, is limited to a single target and 8 seconds cooldown, for most.
