### ISSUE TITLE
Gather 7.2 changes

### ISSUE THREAD

**Issue by domainzero** [domainzero/mythicpl.us#32]
Gonna need to gather all the new 7.2 stuff for site changes.

I already have:
- new ap costs for each point in the artifact weapon
- new affixes (mostly)

What I need:
- new affix combos and schedules (US and EU)
- ~new AK scaling~

**Comment by dreadnip** [comment]
You ever considered putting this all in a simple db/crm combo instead of just plaintext? You could go with SQLite and just commit the db file with the repo.

**Comment by domainzero** [comment]
I've thought about it but haven't had time to do a rewrite.

After all the 7.2 stuff is implemented I might give it a go.

**Comment by Yrdi** [comment]
New AK scaling should be as in this reddit post. 

https://www.reddit.com/r/wow/comments/5z3fup/the_amount_of_traits_you_need_in_715_to_get/deuzhtx/

**Comment by hayatofujii** [comment]
Friend of mine completed an EoA +6 on 3 chests time. Yield on AK26 was 475450.

**Comment by wolfej** [comment]
DHT +10, 2 chest, AK26 = 775,750

**Comment by beardofedu** [comment]
DHT +6, 2 chest, AK 26 = 475,450

**Comment by beardofedu** [comment]
**Artifact Knowledge 26**

 | | MoS | TBD | EoA, DHT, COS | HoV |
|---|---|---|---|---|
2-3 | xxx,xxx | xxx,xxx, | xxx,xxx | xxx,xxx | |
4-6 | xxx,xxx | xxx, xxx | 475,450 | 600,600 | |
7-9 | xxx,xxx | xxx,xxx, | 540,500 | xxx,xxx | |
10+ | xxx,xxx | xxx,xxx, | 775,750 | xxx,xxx | |

**Notes:**
1. It appears the number of chests you get does not matter, just the timer the dungeon has
1. The table was created as a culmination of all the data currently provided and will be updated as more data is available
1. Dungeon groupings will be adjusted as more data becomes available

**Comment by Tobawouhou** [comment]
I ran a few m+ yesterday with AK 26. 

UppK, +3,  300300
BRH and CoS, +4, 475450
UppK, +6, 475450
CoEN, +6, 475450
DHT, +10, 775750
NL, +11, 775750

I sadly can not remember the AP of my HOV+9.

**Comment by CaioEduardo** [comment]
Tier 1: MoS
4 a 6: ?
7 a 9: 325,300
10+: 465,450 (+43%)

(+66% AP compared to Tier 1)
Tier 2: CoS, DHT, Cathedral, Upper Karazhan, Lower Karazhan, VotW, NL, EoA and BRH
4 a 6: 475,450
7 a 9: 540,500 (+13%)
10+: 775,750 (+43%)

(+25% AP compared to Tier 2)
Tier 3: Arcway and HoV
4 a 6: 600,600
7 a 9: 675,650 (+12%)
10+: 1,001,000 (+48%)

**Comment by domainzero** [comment]
:raised_hands:

**Comment by dreadnip** [comment]
1m AP for a single dungeon 🤔

**Comment by Tobawouhou** [comment]
@CaioEduardo Are you sure about the HoV/Arc 675650? I am pretty sure it said 675650 in the tooltip but rewarded 808800

**Comment by beardofedu** [comment]
This might solve everything related to AP:
![AP](http://m.imgur.com/a/AgOBu)

**Comment by beardofedu** [comment]
http://imgur.com/a/AgOBu

**Comment by domainzero** [comment]
That's exactly what I was looking for!
Base value before scaling is awesome. I'll see if I can adjust the calculator script to somehow account for this.

**Comment by dreadnip** [comment]
I could help with this if you want, just DM me on Discord!

**Comment by chuDr3t4** [comment]
+15 base ap
maw 725
arcway hov 1500
everything else 1200

for every level higher (confirmed up to 19)
maw 50
arcway hov 125
everything else 100

**Comment by makinloves** [comment]
The site does not have this week's affix for US.  It is: Teeming, Explosive, and Fortified in that order.

**Comment by domainzero** [comment]
Looks like the script broke. I'll fix it when I get time.

**Comment by dreadnip** [comment]
I did some digging and the culprit is using 25/26 March as reference date. It's been 13 days since the 26th, 13/7 = 1, 1%8=1, 1+1 = **2**, and it's been 14 days since the 25th, 14/7 = 2, 2%8=2, 2+1 = **3**.

This would put the US already in week 3 which is still unknown so ?,?,? appears. I'm still using 28/29 in [my personal version](https://github.com/dreadnip/kirbypl.us/blob/master/assets/js/script.js) of the script and that one returns the correct week.
