### ISSUE TITLE
Keyed still not updated, alternative version.

### ISSUE THREAD

**Issue by bitlyons** [domainzero/mythicpl.us#35]
On the site there is a link to the addon keyed which stopped working in 7.2.  So far the developer has not updated it for 7.2, nor have they responded to questions or comments about the addon in quite a while. Someone else has taken it upon themselves to update and continue the addon [here]( https://mods.curse.com/addons/wow/264479-keyed-2-0). Until the original is updated i think it would be worth while changing the link to the 2.0 version.

**Comment by domainzero** [comment]
Busy today, but will update ASAP.
Thanks!
