### ISSUE TITLE
Wrong AP rewards?

### ISSUE THREAD

**Issue by johannesveje** [domainzero/mythicpl.us#41]
I was look at the calculator, and I think it is using wrong AP rewards. I know it only takes avg dungeons into account, but they still seem wrong. From https://mythicpl.us/assets/grind.js , I got the following base AP rewards:
T1: 500,
T2: 800,
T3: 1000, 
T4: 1200,

and from the other places I am looking they go:
300	475	540	775.

From the history, I can see they have not been changed since 7.2

**Comment by domainzero** [comment]
7.2 launch, for sure.
I can drop the correct values in today sometime and push the change.

**Comment by johannesveje** [comment]
I guess it does not really matter anymore :)
