### ISSUE TITLE
US Weekly Mods Not Correct

### ISSUE THREAD

**Issue by xZora25** [domainzero/mythicpl.us#42]
Website says current week for US is Raging, Volcanic, Tyrannical however it is Teeming, Necrotic, Tyrannical.

**Comment by domainzero** [comment]
Clear your cache if you have visited the site before.
I had to make a change to the script this morning and you may still have a cached version loaded.

**Comment by dlachapelle** [comment]
This week's affix's are wrong as well - looks like there is a different rotation now.

**Comment by domainzero** [comment]
@dlachapelle Try clearing your cache as well.
I had to make a change to the script and you may still have an older version cached.
