### ISSUE TITLE
AP Calculator shows max AK level of 50 should be 40 instead.

### ISSUE THREAD

**Issue by DanielRieske** [domainzero/mythicpl.us#44]
Artifact Power calculator still shows max level 50 which is not obtainable. Should be max level 40 right?.

**Comment by domainzero** [comment]
Yeah. Admittedly the calculator needs some love.
I'll take a look at it when I can. 

I don't have away to discern short, normal, and long run rewards right now either.

**Comment by dreadnip** [comment]
I'm completely lost on the way AP works right now because I quit WoW, but if you have a draft or a rough idea I could look at the code if you want.

**Comment by domainzero** [comment]
Something something scaling something something.

I'll see what I can figure out. I have to gather more information on the way short/med/long dungeons work for rewards.

**Comment by DanielRieske** [comment]
Seeing grind.js and the html on calculator page, it is basically only changing it to 40. The percentages are still the same. On AK level 40 it is an increase of 4,000,000 %.

**Comment by domainzero** [comment]
Gotcha, I've trimmed down to just level 40 for the selections and removed all other options above 40 from the script and will push it here soon.

```Javascript
...
        38: 23700,
	39: 30800,
	40: 40000
};
var apRewards = {
	T1: 500,
	T2: 800,
	T3: 1000, 
	T4: 1200,
}
var ARTIFACT_LEVEL_35 = 35;
var ARTIFACT_LEVEL_52 = 52;
var MAX_ARTIFACT_LEVEL = 101;
var MAX_ARTIFACT_KNOWLEDGE = 40;
...
```
