### ISSUE TITLE
New Chest Rewards

### ISSUE THREAD

**Issue by beardofedu** [domainzero/mythicpl.us#45]
@domainzero just trying to help build out the table for the new weekly rewards. 

| Dungeon Level | ilvl reward | m+ key |
|---------------|-------------|---| 
| 11              |    910         |  | 
| 12              |   915          |  | 
| 13              |   920          |  10 
| 14  | 925  |  | 
| 15  |  930  |  |

**Comment by domainzero** [comment]
For the sake of brevity I shortened the table to be keystone levels 6-15 and removed the m+ key downgrade bit since I don't know if people really care anymore, so don't sweat grabbing m+ key levels after the downgrade I guess.

Thanks for confirming the ilvl rewards!

**Comment by beardofedu** [comment]
Looks great @domainzero , closing issue since you handled it. 👍
