### ISSUE TITLE
Next week affixes are off

### ISSUE THREAD

**Issue by ceylina** [domainzero/mythicpl.us#49]
![untitled](https://user-images.githubusercontent.com/9342192/28049766-14d92962-65bf-11e7-93df-68d89f007fcd.jpg)

Your list of weekly are correct(?) but your next week isn't showing correctly as per that list

Next week shouldn't be
Bursting, Skittish, Tyrannical
Should be 
Sanguine | Volcanic | Fortified

So either the list of affixes is out of order or the next week listing is

**Comment by domainzero** [comment]
Thanks for the heads up. The script I'm using to track next week and week after next probably went off the rails. I'll get it fixed tomorrow when I can.

**Comment by beardofedu** [comment]
@domainzero just wanted to confirm this week (July 18th reset) is:

 Bursting Skittish Tyrannical
