### ISSUE TITLE
Depending on resolution the next "page" below can be seen

### ISSUE THREAD

**Issue by Auchindoun** [domainzero/mythicpl.us#5]
<img width="1678" alt="screen shot 2016-11-29 at 3 52 33 pm" src="https://cloud.githubusercontent.com/assets/11381794/20730504/ecb55488-b64b-11e6-9061-835890cb496a.png">

**Comment by domainzero** [comment]
This is definitely just hacked together right now and the "next page" is just spaced down by a bottom margin on the affixes div.

I could just... make the margin bigger >:D

**Comment by JanoschVG** [comment]
You might want to set your "above the fold" section to `height: 100vh;`

In case you're not familiar with vh: it's a viewport unit (meaning viewport height) and is [supported in pretty much all browsers](http://caniuse.com/#feat=viewport-units)

**Comment by domainzero** [comment]
Adjusted to make it a lot less hacky. Thanks for the tip. Forgot about the height stuff!
