### ISSUE TITLE
Mark current affixes in "AFFIX EFFECTS" list

### ISSUE THREAD

**Issue by sheridan-dev** [domainzero/mythicpl.us#50]
It would be easier to quickly check details about current affixes if they were marked (with a border for example).

**Comment by domainzero** [comment]
Sorry it took forever for me to get back to you.
I've been meaning to implement something like this for a long time but just haven't had time to get around to it. I'll try to work on it this week.

**Comment by amarques** [comment]
Hello @domainzero,
I made this change on my fork version 👍 

If want merge to master, fell free :)

Ty and kind regards

**Comment by domainzero** [comment]
Fixed in #60 by @amarques
