### ISSUE TITLE
Mythic Loot Table

### ISSUE THREAD

**Issue by SinisterJo** [domainzero/mythicpl.us#56]
The some of the loot levels for mythics are incorrect. Mythic 6 awards ilvl 900 gear from dungeon.

**Comment by domainzero** [comment]
Thank you! I'll get it updated.
Do you have any other examples that are incorrect?

**Comment by amarques** [comment]
@SinisterJo and @domainzero, i fixed that and 2 or 3 wrong info.
I hope made a PR as soon as posible.

KR

**Comment by amarques** [comment]
fixed on #63

**Comment by amarques** [comment]
Closed
