### ISSUE TITLE
Translate project

### ISSUE THREAD

**Issue by amarques** [domainzero/mythicpl.us#57]
Sup guys
Amazing job, i really love u page.

Question: - Its possible open a language translation session? I could help with portuguese-br and spanish languages translations :) I think will be a nice touch to the ppl from another countries.

**Comment by domainzero** [comment]
That would be awesome!
Feel free to fork the project and start translating. I'll merge in anything you have and can hopefully set up pages that load when browser localization is detected.

**Comment by amarques** [comment]
Nice,
On progres... https://i.imgur.com/BpbN9lo.png
Im using www.openxrest.com/translatejs to translate. I never fork a project, so, maybe i will need some help to commit a change on the project.

Ty, and gl

**Comment by amarques** [comment]
I have 70% already translated to Spanish and Portuguese in my forked version.
Still working on it.

**Comment by amarques** [comment]
Hello @domainzero,
I dont know if u saw my previous message. I finished the translation.

To help u with tests, i publish on my personal server (on a hide folder) the last stable version:
http://andersonmarques.com.br/mythicpl.us/index.html

If u need some additional info, please let me know.

Ty and kr

**Comment by amarques** [comment]
Ty man. Code merged, I’m closing this issue
