### ISSUE TITLE
Translation option suggestion

### ISSUE THREAD

**Issue by Pobre** [domainzero/mythicpl.us#61]
Good day,

**First things first, thanks for the amazing site, all contributors, the translation works flawless.**
The problem comes when someone people doesn't play the game in their native language which can cause some trouble finding information. I would like to suggest to give the user the option to change language (a simple combobox/listbox to choose). It would be a great addition.

**Comment by domainzero** [comment]
Sure! I'll get that implemented.

**Comment by domainzero** [comment]
Got some buttons built but they're breaking the affixes when the language is changed.

**Comment by amarques** [comment]
Ty by suggestion @Pobre, i will try check that too.
If u need some help about this part @domainzero, please let me know.

**Comment by domainzero** [comment]
@Pobre @amarques 
Implemented a menu to change language.

**Comment by amarques** [comment]
I have the language selector, but i have a little issue with translate API r.io week affix.
Im working on that.

@domainzero if u could help me with the style will be great.

**Comment by amarques** [comment]
Solved by @domainzero

**Comment by domainzero** [comment]
🎉

**Comment by Pobre** [comment]
Thank you very much guys. Translation was the best thing you guys did.
