### ISSUE TITLE
Sometimes the Graphs page dont get the google spreadsheet and the results are: undefined

### ISSUE THREAD

**Issue by amarques** [domainzero/mythicpl.us#69]

**Comment by amarques** [comment]
I think is a JS lib issue but I don’t know how fix it

**Comment by domainzero** [comment]
Yeah, I'm not sure how to fix this.
I think it's an issue with tabletop.

**Comment by amarques** [comment]
@DavidEspinola - Este ya es más chungo David :) Te comparto por si tienes tiempo y o alguna idea de como solucionarlo, estaría dpm.

**Comment by DavidEspinola** [comment]
Le puedo intentar echar un vistazo esta tarde ¿Sabes cómo reproducir el
error o es muy errático?

**Comment by amarques** [comment]
LOL, i see that right now! Amazing job @DavidEspinola! U are the best!!! Works like a charm!
