### ISSUE TITLE
Volcanic affix description - add "ranged"

### ISSUE THREAD

**Issue by bettybae** [domainzero/mythicpl.us#7]
Volcanic **always** prefers ranged players, which means you need to bring more than one ranged or suffer the consequences. If no players are ranged, then volcanic targets random melee players.

**Comment by domainzero** [comment]
Fixed, thanks!

**Comment by Gnarfoz** [comment]
Doesn't it actually work based off your distance to enemies?
I've had plenty of volcanoes spawn under me as a tank with only one other melee in sight.

**Comment by xepheris** [comment]
It's more than that, you can see it perfectly at CoS last boss with X+Volcanic+Tyrannical. With enough mirror versions of him, Volcanic will spawn in melee just as consistent as in ranged => 90/10 at the start down to 50/50 at the end the more enemies you have.
