### ISSUE TITLE
Suggestions / Ideas

### ISSUE THREAD

**Issue by xepheris** [domainzero/mythicpl.us#8]
<s>– add addon Keyed
– add addon KeyBooster

DHT tips:
– you can skip all the trash between 1st and 2nd boss by mounting through and hiding behind the stones to the right of the 2nd boss where the satyrs near the way to SoX stand. Hide behind the big stone at the entrance and wait 30s, then they will reset. If you cleared everything until then, you need to clear up to approx. 64% there to finish perfectly. </s> rip
– tanks can dodge the bear charge on 1st boss by moving out the charge direction

<s>– Maw of Souls:
– for 100% you need:
1. all the trash before 1st boss (obviously)
2. on the Naglfar, the first group to the right corridor as soon as you are on board
3. the three small Helhounds that patrol to the last segment of the lower part of the ship
4. after the 2nd boss, one side completely and the Helarjar Champion at the start of the other side
– on Necrotic, pull the last miniboss far back, else your tank will suffer through 24769829 stacks due to the adds</s>

<s>
– Arcway:
– sometimes you can interrupt the Devour ability of the spiders by fearing them (not 100% for some reason)
– warlocks can enslave the Draenei warlocks; write a macro to buff a useful target with their % haste & % dmg increased buff, without macro they cast it on a random target
– mages can spellsteal that buff aswell
</s>

– Eye of Azshara
– near Serpentrix, pull ca. 4 crab groups at the same time and kite them to get ca. 12% of progress to avoid later need to do murloc camps or a snail
– skipping 2nd boss for 3rd and doing it then after disables winds & seagulls for respective bosses

– Vault of the Wardens
– on higher m+, always do the blade mistress with the dogs after the 2nd boss because you need the % and the nathrezim occasionally may oneshot with Meteor
– tank the second boss behind of where he stands at the start and never move unless he spawns the Pandaria adds. After teleporting the boss will always come back. You avoid moving and the eyes this way.

**Comment by domainzero** [comment]
Thank you for the tips! I'll start getting these into a guide format.

**Comment by domainzero** [comment]
Added the addons. Working on guides.

**Comment by domainzero** [comment]
Edited main comment with stuff i have covered.
